################################################################
# This is the DEVELOPMENT config file.
# Any settings here will override those in _config.yml
# 
# Run this command to work locally:
# `jekyll serve --config _config.yml,_config_dev.yml`
# 
# This file is *NOT* rebuilt automatically.
# If you change this file, please restart the server process
###############################################################

# Serving
port: 4000
host: 127.0.0.1
baseurl: "" # ex: `/project` if serving from `http://localhost:4000/project/`
url: "" # the base hostname & protocol for your site (can leave it blank for local dev)

# Environment - use this in your logic:
# {% if site.environment == "development" %} do things {% endif %}
environment: development

# livereload
livereload: true # Watch your browser reload upon changes

# Build settings
sass:
  style: expanded # options: nested, compact, expanded, compressed