################################################################
# This is the PRODUCTION config file.
# 
# Run this command when ready to deploy/upload to your server:
# `jekyll build`
# 
# This file is *NOT* rebuilt automatically.
# If you change this file, please restart the server process
###############################################################

# Serving
baseurl: "/jekyll-starter" # is your site served from subdirectory?
url: "https://luclemo.github.io" # the hostname & protocol for your site

# Outputting
permalink: /blog/:title/

# Build settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
sass:
  style: compressed
highlighter: rouge
autoprefixer:
  browsers:
  - last 2 versions

# Inlcudes & excludes
include: ["_pages"] # custom directory to organize pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
- jekyll-autoprefixer